(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const e=$('#toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}};
const api=window.binerCore||{};
const st=document.createElement('style');st.textContent=`#v050{padding-bottom:30px}#v050 .vhead{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:22px;border:1px solid #ffffff12;border-radius:20px;background:#0d1421;margin-bottom:16px}#v050 .vhead p{color:#8b9ab0;margin:6px 0 0}.vgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.vcard{background:#0d1421;border:1px solid #ffffff10;border-radius:17px;padding:17px}.vcard.wide{grid-column:1/-1}.vcard h3{margin:4px 0 7px}.vcard p,.vmuted{color:#8796aa;font-size:13px}.vrow{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;background:#080e18;border-radius:11px;margin-top:7px}.vrow small{color:#7d8ca2}.vactions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.vinput{width:100%;box-sizing:border-box;padding:11px 13px;border-radius:11px;border:1px solid #ffffff14;background:#080e18;color:#fff;outline:none}.vlist{max-height:300px;overflow:auto}.vstat{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.vstat>div{padding:10px;background:#080e18;border-radius:10px}.vstat b{display:block;font-size:18px}.vstat small{color:#748298}@media(max-width:1000px){.vgrid{grid-template-columns:1fr}.vcard.wide{grid-column:auto}.vstat{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(st);
const sec=document.createElement('section');sec.id='v050';sec.className='section hidden-section';sec.innerHTML=`<div class="vhead"><div><small>BINERLAUNCHER 0.5.0</small><h2>مرکز مدیریت Minecraft</h2><p>مود، مودپک، Instance، Performance، World، Resource Pack، Shader، Backup، Download و Logs.</p></div><b>15 TOOLS</b></div><div class="vgrid">
<article class="vcard wide"><h3>Instance Manager</h3><p>ساخت و مدیریت محیط‌های مستقل Minecraft.</p><div class="vactions"><input id="viName" class="vinput" placeholder="نام Instance" style="max-width:300px"><button class="primary" id="viCreate">ساخت Instance</button><button class="ghost" id="viRefresh">Refresh</button></div><div class="vlist" id="viList"></div></article>
<article class="vcard wide"><h3>Mod Manager</h3><div class="vactions"><input id="vmSearch" class="vinput" placeholder="جستجوی Mod در Modrinth" style="max-width:420px"><button class="primary" id="vmGo">جستجو</button></div><div class="vlist" id="vmList"></div></article>
<article class="vcard wide"><h3>Modpack Manager</h3><p>Manifest بساز و ذخیره کن.</p><div class="vactions"><input id="vpName" class="vinput" placeholder="نام Modpack" style="max-width:280px"><button class="primary" id="vpExport">Export Modpack</button><button class="ghost" id="vpImport">Import Manifest</button></div></article>
<article class="vcard"><h3>Performance Center</h3><div class="vstat"><div><small>RAM</small><b id="vRam">—</b></div><div><small>Preset</small><b id="vPreset">—</b></div><div><small>Fast</small><b id="vFast">—</b></div><div><small>Java</small><b>AUTO</b></div></div><div class="vactions"><button class="primary" id="vBoost">Apply Performance</button></div></article>
<article class="vcard"><h3>Repair Center 2.0</h3><p>بررسی سلامت نصب و فایل‌های Minecraft.</p><div id="vDiag" class="vmuted">آماده بررسی.</div><div class="vactions"><button class="primary" id="vScan">Scan</button><button class="ghost" id="vFix">Repair</button></div></article>
<article class="vcard"><h3>World Manager</h3><div id="vWorlds" class="vlist"><div class="vmuted">یک Instance انتخاب کنید.</div></div><div class="vactions"><button class="primary" id="vWorldRefresh">Refresh Worlds</button><button class="ghost" id="vWorldFolder">Open Folder</button></div></article>
<article class="vcard"><h3>Resource Pack & Shader</h3><div class="vactions"><button class="primary" id="vResource">Resource Packs</button><button class="ghost" id="vShader">Shaders</button></div></article>
<article class="vcard"><h3>Backup Center</h3><div id="vBackups" class="vlist"><div class="vmuted">Backupها آماده بارگذاری.</div></div><div class="vactions"><button class="primary" id="vBackup">Create Backup</button><button class="ghost" id="vBackRefresh">Refresh</button></div></article>
<article class="vcard wide"><h3>Download Manager</h3><div id="vDownloads" class="vlist"><div class="vmuted">دانلود فعالی وجود ندارد.</div></div><button class="ghost" id="vDlRefresh">Refresh Downloads</button></article>
<article class="vcard wide"><h3>Minecraft Log Viewer</h3><div id="vLogs" style="height:220px;overflow:auto;padding:12px;background:#060a11;border-radius:11px;font:12px Consolas,monospace;white-space:pre-wrap;color:#b8c4d5">منتظر Log...</div><div class="vactions"><button class="ghost" id="vLogClear">Clear</button><button class="ghost" id="vCrash">Open Crash Reports</button></div></article>
<article class="vcard"><h3>Server Center</h3><input id="vHost" class="vinput" value="Play.BinerCraft.ir"><div class="vactions"><button class="primary" id="vPing">Check Server</button></div><div id="vServer" class="vmuted"></div></article>
<article class="vcard"><h3>Account / Profile</h3><div id="vAccounts" class="vlist"></div><div class="vactions"><input id="vAccount" class="vinput" placeholder="Offline username" style="max-width:220px"><button class="primary" id="vAddAccount">Add Account</button></div></article>
<article class="vcard"><h3>Screenshot Manager</h3><p>دسترسی سریع به Screenshotهای Minecraft.</p><button class="primary" id="vScreens">Open Screenshots</button></article>
<article class="vcard"><h3>Launcher Customization</h3><p>GUI Scale و تنظیمات ظاهری لانچر.</p><div class="vactions"><button class="primary" id="vScaleDown">Zoom −</button><button class="ghost" id="vScaleUp">Zoom +</button></div></article></div>`;document.querySelector('.content')?.appendChild(sec);
const nav=document.querySelector('.sidebar nav');if(nav&&!nav.querySelector('[data-section="v050"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.section='v050';b.innerHTML='<i class="fa-solid fa-toolbox" aria-hidden="true"></i><span>مرکز مدیریت</span><i>0.5</i>';nav.appendChild(b);b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.section').forEach(x=>x.classList.toggle('hidden-section',x.id!=='v050'))}};
let selected='';
const renderInstances=async()=>{try{const xs=await api.instances.list();const a=Array.isArray(xs)?xs:(xs?.instances||[]);$('#viList').innerHTML=a.length?a.map(x=>`<div class="vrow"><span><b>${esc(x.name||x.id||'Instance')}</b><br><small>${esc(x.version||'Unknown')} • ${esc(x.loader||'vanilla')}</small></span><span><button class="ghost" data-open="${esc(x.id||x.name)}">Open</button> <button class="ghost" data-del="${esc(x.id||x.name)}">Delete</button></span></div>`).join(''):'<div class="vmuted">Instanceی وجود ندارد.</div>';$$('[data-open]').forEach(b=>b.onclick=()=>{selected=b.dataset.open;api.instances.open?.(selected);renderWorlds()});$$('[data-del]').forEach(b=>b.onclick=async()=>{await api.instances.delete(b.dataset.del);renderInstances()})}catch(e){$('#viList').textContent=e.message}};
$('#viCreate').onclick=async()=>{const name=$('#viName').value.trim()||'Biner Instance';try{await api.instances.create({name,version:'1.21.11',loader:'vanilla'});$('#viName').value='';toast('Instance ساخته شد ✓');renderInstances()}catch(e){toast(e.message)}};$('#viRefresh').onclick=renderInstances;
const modSearch=async()=>{const q=$('#vmSearch').value.trim();if(!q)return;$('#vmList').innerHTML='<div class="vmuted">در حال جستجو...</div>';try{const r=await fetch('https://api.modrinth.com/v2/search?query='+encodeURIComponent(q)+'&limit=12&facets='+encodeURIComponent(JSON.stringify([["project_type:mod"]])));const d=await r.json();$('#vmList').innerHTML=(d.hits||[]).map(x=>`<div class="vrow"><span><b>${esc(x.title)}</b><br><small>${esc(x.description||'')}</small></span><button class="ghost" data-slug="${esc(x.slug)}">Open</button></div>`).join('')||'<div class="vmuted">نتیجه‌ای پیدا نشد.</div>';$$('[data-slug]').forEach(b=>b.onclick=()=>window.biner?.openExternal?.('https://modrinth.com/mod/'+b.dataset.slug))}catch(e){$('#vmList').textContent=e.message}};$('#vmGo').onclick=modSearch;
$('#vpExport').onclick=async()=>{const n=$('#vpName').value.trim()||'BinerModpack',p=await window.biner.getProfile(),m={formatVersion:1,name:n,minecraft:{version:p?.version||'1.21.11',loader:p?.loader||'vanilla'},generatedBy:'BinerLauncher 0.5.0',createdAt:new Date().toISOString()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(m,null,2)],{type:'application/json'}));a.download=n.replace(/[^\w-]+/g,'_')+'.json';a.click();toast('Modpack export شد ✓')};$('#vpImport').onclick=()=>toast('Import manifest در نسخه بعدی تکمیل می‌شود.');
const updatePerf=async()=>{const p=await window.biner.getProfile();const mb=p?.memory||4096;$('#vRam').textContent=mb+' MB';$('#vPreset').textContent=mb>=12288?'Extreme':mb>=8192?'Performance':mb>=4096?'Balanced':'Safe';$('#vFast').textContent=p?.fastMode!==false?'ON':'OFF'};$('#vBoost').onclick=async()=>{const p=await window.biner.getProfile();p.memory=Math.max(2048,Math.min(16384,Math.round((Number(navigator.deviceMemory)||8)*512)));p.fastMode=true;p.customArgs=['-XX:+UseG1GC','-XX:+ParallelRefProcEnabled','-XX:MaxGCPauseMillis=50','-XX:+UnlockExperimentalVMOptions','-XX:+DisableExplicitGC'];await window.biner.saveProfile(p);updatePerf();toast('Performance بهینه شد ✓')};
$('#vScan').onclick=async()=>{try{$('#vDiag').textContent=JSON.stringify(await window.biner.repairScan())}catch(e){$('#vDiag').textContent=e.message}};$('#vFix').onclick=async()=>{try{$('#vDiag').textContent=JSON.stringify(await window.biner.repairFix())}catch(e){$('#vDiag').textContent=e.message}};
const renderWorlds=async()=>{if(!selected)return;try{const a=await api.worlds.list(selected),xs=Array.isArray(a)?a:(a?.worlds||[]);$('#vWorlds').innerHTML=xs.length?xs.map(x=>`<div class="vrow"><span>${esc(x.name||x.id||x)}</span><button class="ghost" data-world="${esc(x.id||x.name||x)}">Delete</button></div>`).join(''):'<div class="vmuted">Worldی پیدا نشد.</div>';$$('[data-world]').forEach(b=>b.onclick=async()=>{await api.worlds.delete({instanceId:selected,name:b.dataset.world});renderWorlds()})}catch(e){$('#vWorlds').textContent=e.message}};$('#vWorldRefresh').onclick=renderWorlds;$('#vWorldFolder').onclick=async()=>window.biner.openFolder((await window.biner.folders()).root);$('#vResource').onclick=async()=>{const f=await window.biner.folders();window.biner.openFolder(f.root+'\\resourcepacks')};$('#vShader').onclick=async()=>{const f=await window.biner.folders();window.biner.openFolder(f.root+'\\shaderpacks')};
const renderBackups=async()=>{try{const a=await api.backups.list(),xs=Array.isArray(a)?a:(a?.backups||[]);$('#vBackups').innerHTML=xs.length?xs.map(x=>`<div class="vrow"><span>${esc(x.name||x.id||x)}</span><small>${esc(x.createdAt||'')}</small></div>`).join(''):'<div class="vmuted">Backupی وجود ندارد.</div>';}catch(e){$('#vBackups').textContent=e.message}};$('#vBackup').onclick=async()=>{try{await api.backups.create({instanceId:selected});toast('Backup ساخته شد ✓');renderBackups()}catch(e){toast(e.message)}};$('#vBackRefresh').onclick=renderBackups;
const renderDownloads=async()=>{try{const a=await window.biner.activeDownloads(),xs=Array.isArray(a)?a:Object.values(a||{});$('#vDownloads').innerHTML=xs.length?xs.map(x=>`<div class="vrow"><span>${esc(x.name||x.id||'Download')}</span><b>${esc(x.progress??0)}%</b></div>`).join(''):'<div class="vmuted">دانلود فعالی وجود ندارد.</div>'}catch(e){$('#vDownloads').textContent=e.message}};$('#vDlRefresh').onclick=renderDownloads;
window.biner.onLog?.(m=>{const e=$('#vLogs');e.textContent+=(e.textContent==='منتظر Log...'?'':'\n')+String(m);e.scrollTop=e.scrollHeight});$('#vLogClear').onclick=()=>$('#vLogs').textContent='';$('#vCrash').onclick=()=>window.biner.openCrashReports();$('#vPing').onclick=async()=>{try{const r=await window.biner.serverStatus({host:$('#vHost').value.trim(),port:25565});$('#vServer').textContent=r.online?'ONLINE • '+r.ping+'ms':'OFFLINE'}catch(e){$('#vServer').textContent=e.message}};
const renderAccounts=async()=>{try{const a=await window.biner.accounts.list(),xs=Array.isArray(a)?a:(a?.accounts||[]);$('#vAccounts').innerHTML=xs.length?xs.map(x=>`<div class="vrow"><span>${esc(x.username||x.name||x.id)}</span><button class="ghost" data-account="${esc(x.id)}">Activate</button></div>`).join(''):'<div class="vmuted">حسابی ثبت نشده.</div>';$$('[data-account]').forEach(b=>b.onclick=async()=>{await window.biner.accounts.activate(b.dataset.account);renderAccounts()})}catch(e){$('#vAccounts').textContent=e.message}};$('#vAddAccount').onclick=async()=>{const n=$('#vAccount').value.trim();if(!n)return;await window.biner.accounts.addLocal(n);$('#vAccount').value='';renderAccounts()};$('#vScreens').onclick=async()=>{const f=await window.biner.folders();window.biner.openFolder(f.root+'\\screenshots')};$('#vScaleDown').onclick=async()=>window.biner.setZoom(Math.max(.7,(await window.biner.getZoom())-.1));$('#vScaleUp').onclick=async()=>window.biner.setZoom(Math.min(1.4,(await window.biner.getZoom())+.1));
renderInstances();renderBackups();renderDownloads();renderAccounts();updatePerf();
})();